### ISSUE TITLE
[CI] Increase max_user_watches during agent setup

### ISSUE THREAD

**Issue by n0izn0iz** [berty/berty#1604]
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

or else CI will break on react-native app builds

```
> Task :app:bundleReleaseJsAndAssets
internal/fs/watchers.js:173
    throw error;
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/buildkite-agent/go/src/berty.tech/berty/js/packages/berty-app/node_modules/core-js/fn/number/virtual'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1258:11)
    at NodeWatcher.watchdir (/home/buildkite-agent/go/src/berty.tech/berty/js/node_modules/sane/src/node_watcher.js:159:22)
    at Walker.<anonymous> (/home/buildkite-agent/go/src/berty.tech/berty/js/node_modules/sane/src/common.js:109:31)
    at Walker.emit (events.js:198:13)
    at /home/buildkite-agent/go/src/berty.tech/berty/js/node_modules/walker/lib/walker.js:69:16
    at go$readdir$cb (/home/buildkite-agent/go/src/berty.tech/berty/js/packages/berty-app/node_modules/graceful-fs/graceful-fs.js:187:14)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)

> Task :app:bundleReleaseJsAndAssets FAILED
```

**Comment by dominictobias-bullish** [comment]
This is still in issue running tests e.g. vitest on a larger project. We have all unnecessary files excluded in `vitest`
